### ISSUE TITLE
managers should be able to update all containers 

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-registry#6]
Hey. I was reading that doc about LXC / OverlayFS
https://the.binbashtheory.com/using-overlayfs-with-lxc/
And so, I have a stupid question: let's say that there is high security issue in bash. Will I need to upgrade all my singularity containers ?

If the answer is "yes" some management tools on a singularity registry would be great v :yum:
Upgrade every containers on that registry in a quick / clean way.

**Comment by remyd1** [comment]
:+1: see also  #9 

Rémy
