### ISSUE TITLE
Upgrading all images from a registry

### ISSUE THREAD

**Issue by remyd1** [singularityhub/singularity-registry#9]
Hi,

This is not an issue but a feature request. The main idea is to add the possibility as a registry admin, to upgrade all images from a registry and check logs for any problem, or at least, container by container (or with a scheduler).
Container by container would be as easy as 
```bash
singularity exec $IMG yum update
```
 or 
```bash
singularity exec $IMG "apt-get update && apt-get dist-upgrade"
```
. For all containers, a loop can do the job. What would be needed is the output of these commands for the singularity-registry admin, in an admin panel view.

Best regards,
Rémy

PS : It refers to [this issue](https://github.com/singularityhub/singularityhub.github.io/issues/34#issuecomment-311961959)

**Comment by vsoch** [comment]
@remyd1 for your institution, where would the update likely occur? What I've anticipated so far is something like:

 - A SLURM/SGE job 
 - a node allocated for building
 - a virtual machine (more advanced clusters)

For your cluster, what would you see as being the ideal workflow?

**Comment by remyd1** [comment]
I think the best solution is something like 2 virtual machines (vagrant + libvirt) on the same and dedicated host:
  - A registry machine, with the Web server,
  - A building machine for tests, builds, upgrades.

Or 2 containers... ;-) So, there will be nested containers.

Kind regards,
Rémy

**Comment by vsoch** [comment]
so you have a cluster that would support a Dockerized application? Or a web server? This is also the case for TACC, but not for Stanford, for example.

**Comment by remyd1** [comment]
No, I would use it apart from the cluster, for tests, with a VM configuration similar to my compute nodes.

Another solution would be to use nested containers (singularity in another container ?).

Otherwise that means you need to use the libdrmaa python library to submit the job like you suggested (with a job scheduler).

**Comment by remyd1** [comment]
The advantage of using nested container is that it might be included in some docker orchestrator... Using swarm, k8s, mesos...

**Comment by remyd1** [comment]
In fact it depends mostly on the way we want to do it...

  - One big upgrade job running on the cluster and queued like every job,
  - An upgrade service running in the background on a dedicated machine(s) (could be bare-metal, VM(s), container(s)

That is your choice, but my first idea was the second option; but maybe I am wrong.

**Comment by vsoch** [comment]
hey @remyd1 when you have a chance to check out the current sregistry (https://github.com/singularityhub/sregistry) could you reopen the issue there? Thanks!
